@startuml
left to right direction

object Interface
object Controller
object Service
object Repository

Interface -> Controller : create()
Controller -> Service : save()
Service -right-> Repository : save()

@enduml
